### ISSUE TITLE
Import error with opportunity dataset

### ISSUE THREAD

**Issue by IKKIM00** [Hangwei12358/cross-person-HAR#1]
Hello! 
I am trying to run the code but it seems like there is no function named as `opp_sliding_window` in `utils.py`
I tried `python main_oppr.py --target_domain S1` 
and the error message says 
in file `data_preprocess_oppr.py` 
`from utils import get_sample_weights, opp_sliding_window, opp_sliding_window_w_d`
`ImportError: cannot import name 'opp_sliding_window'`
I also looked through `utils.py` but there is no function named as `opp_sliding_window`

Thank you!

**Comment by Hangwei12358** [comment]
Hi IKKIM00,

The functions `opp_sliding_window` and `opp_sliding_window_w_d` are designed for general settings and the cross-person setting respectively, hence I removed the former function from the `utils.py` file in order to keep this repo neat. Sorry for the confusion caused. 
 
For this project, simply delete the function `opp_sliding_window` from 
`from utils import get_sample_weights, opp_sliding_window, opp_sliding_window_w_d` since it is not used for pre-processing in current repo.
